import React from 'react';

function index() {
    return (
        <div>
            
        </div>
    );
}

export default index;
// ESTE ARCHIVO ES NECESARIO PORQUE EN PRODUCCION, CUANDO SE EJECUTAN RUTAS DE CLIENTE COMO /app
// EL SERVIDOR BUSCA LA CARPETA /app EN PAGES Y NECESITA UNA PAGINA QUE MOSTRAR
// ENTONCES LE DAMOS UNA PAGINA EN BLANCO QUE EL SERVIDOR MUESTRE, Y LUEGO QUE EL FRONT-END SE 
//ENCARGUE DE LAS RUTAS DE CLIENTE.
